server:
  port: 8081
spring:
  application:
    name: ribbon
eureka:
  client:
    service-url:
      default-zone: ${eureka.instance.ip-address}:8761/eureka/
  instance:
    ip-address: 192.168.22.5
    instance-id: ${eureka.instance.ip-address}:${server.port}-${spring.application.name}